# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import cctv_stream_pb2 as cctv__stream__pb2


class CCTVStreamStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendFrame = channel.unary_unary(
                '/cctv_stream.CCTVStream/SendFrame',
                request_serializer=cctv__stream__pb2.Request.SerializeToString,
                response_deserializer=cctv__stream__pb2.Response.FromString,
                )
        self.SendFrameStream = channel.unary_stream(
                '/cctv_stream.CCTVStream/SendFrameStream',
                request_serializer=cctv__stream__pb2.Request.SerializeToString,
                response_deserializer=cctv__stream__pb2.Response.FromString,
                )


class CCTVStreamServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendFrame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendFrameStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CCTVStreamServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.SendFrame,
                    request_deserializer=cctv__stream__pb2.Request.FromString,
                    response_serializer=cctv__stream__pb2.Response.SerializeToString,
            ),
            'SendFrameStream': grpc.unary_stream_rpc_method_handler(
                    servicer.SendFrameStream,
                    request_deserializer=cctv__stream__pb2.Request.FromString,
                    response_serializer=cctv__stream__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cctv_stream.CCTVStream', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CCTVStream(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cctv_stream.CCTVStream/SendFrame',
            cctv__stream__pb2.Request.SerializeToString,
            cctv__stream__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendFrameStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/cctv_stream.CCTVStream/SendFrameStream',
            cctv__stream__pb2.Request.SerializeToString,
            cctv__stream__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
